baseurl = "/"
title = "Tyma"
description = "I've been thinking.."
languageCode = "en-us"
paginate = "10"
theme = "risotto"
mainSections = ["post"] # Moved to the root level!

[author] # Lowercased
  name = "Paul Tyma"
  avatar = "img/avatar.png"

[params] # Lowercased
  subtitle = "I've been thinking"
  description = "Tyma's Blog"
  bio = "I've been thinking"
  copyright = "Tyma"
  opengraph = true
  twitter_cards = true
  readmore = false
  authorbox = true
  toc = false
  post_navigation = true
  post_meta = ["date", "categories", "translations"]
  dateformat = "2006-01-02"
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  highlightColor = "#e22d30"
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.sidebar] # Lowercased
  home = "right"
  list = "left"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[params.widgets] # Lowercased
  recent_num = 5
  tags_counter = false

[params.widgets.social] # Lowercased
  linkedin = "paul-tyma-8a9b9217"

[params.social]
  linkedin = "paul-byron-tyma-8a9b9217"   # Just your LinkedIn identifier
  email = "paul@tyma.com"                 # Your full email address
  github = "paultyma"                     # Just your GitHub username (if you have one)

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1



