#+STARTUP: content
#+AUTHOR: Paul Tyma
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:


** A Google Interviewing Story
    :PROPERTIES:
    :EXPORT_DATE: 2020-01-09
    :EXPORT_FILE_NAME: post-title-in-slug-form
    :END:

A few years ago I was entering the Silicon Valley job market and at that time looking for senior engineering positions. A good rule of thumb about interviewing if you haven't done it in awhile is to at least somewhat accept that you'll probably make a few mistakes on your first few tries. Simply, don't go for your dream job first. There are a million nuances to interviewing that you've forgotten, and a few up-front, not-so-important interviews first will educate (or re-educate) about them.



For example, if the two strings were:

    #+BEGIN_SRC bash -l 7 :hl_lines 8
    String 1: ABCDEFGHLMNOPQRS
    String 2: DCGSRQPOM
    #+END_SRC


You'd get true as every character in string2 is in string1. If the two strings were:


** The Young Man's Business Model
    :PROPERTIES:
    :EXPORT_DATE: 2020-01-09
    :EXPORT_FILE_NAME: post-title-in-slug-form
    :END:

so i said.. hiya
You'd get true as every character in string2 is in string1. If the two strings were:




** Post Sub-Heading
     This is another section within the post.

** TODO Draft Post Title
    :PROPERTIES:
    :EXPORT_FILE_NAME: draft-post-title
    :END:

    This article *will* be exported but will be marked ~draft = true~ in the front matter.

* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (add-hook 'after-save-hook #'org-hugo-export-wim-to-md-after-save :append :local)
# eval: (auto-fill-mode 1)
# End:
